Controllers/TblAlumnoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ControlEscolar.Models;

namespace ControlEscolar.Controllers
{
    public class TblAlumnoesController : Controller
    {
        private readonly EscuelaContext _context;

        public TblAlumnoesController(EscuelaContext context)
        {
            _context = context;
        }

        // GET: TblAlumnoes
        public async Task<IActionResult> Index()
        {
              return _context.TblAlumnos != null ? 
                          View(await _context.TblAlumnos.ToListAsync()) :
                          Problem("Entity set 'EscuelaContext.TblAlumnos'  is null.");
        }

        // GET: TblAlumnoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TblAlumnos == null)
            {
                return NotFound();
            }

            var tblAlumno = await _context.TblAlumnos
                .FirstOrDefaultAsync(m => m.IdAlumno == id);
            if (tblAlumno == null)
            {
                return NotFound();
            }

            return View(tblAlumno);
        }

        // GET: TblAlumnoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TblAlumnoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdAlumno,Nombre,Apellidos,Correo,Telefono")] TblAlumno tblAlumno)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tblAlumno);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tblAlumno);
        }

        // GET: TblAlumnoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TblAlumnos == null)
            {
                return NotFound();
            }

            var tblAlumno = await _context.TblAlumnos.FindAsync(id);
            if (tblAlumno == null)
            {
                return NotFound();
            }
            return View(tblAlumno);
        }

        // POST: TblAlumnoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdAlumno,Nombre,Apellidos,Correo,Telefono")] TblAlumno tblAlumno)
        {
            if (id != tblAlumno.IdAlumno)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tblAlumno);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TblAlumnoExists(tblAlumno.IdAlumno))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tblAlumno);
        }

        // GET: TblAlumnoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TblAlumnos == null)
            {
                return NotFound();
            }

            var tblAlumno = await _context.TblAlumnos
                .FirstOrDefaultAsync(m => m.IdAlumno == id);
            if (tblAlumno == null)
            {
                return NotFound();
            }

            return View(tblAlumno);
        }

        // POST: TblAlumnoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TblAlumnos == null)
            {
                return Problem("Entity set 'EscuelaContext.TblAlumnos'  is null.");
            }
            var tblAlumno = await _context.TblAlumnos.FindAsync(id);
            if (tblAlumno != null)
            {
                _context.TblAlumnos.Remove(tblAlumno);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TblAlumnoExists(int id)
        {
          return (_context.TblAlumnos?.Any(e => e.IdAlumno == id)).GetValueOrDefault();
        }
    }
}

Controllers/TblCicloesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ControlEscolar.Models;

namespace ControlEscolar.Controllers
{
    public class TblCicloesController : Controller
    {
        private readonly EscuelaContext _context;

        public TblCicloesController(EscuelaContext context)
        {
            _context = context;
        }

        // GET: TblCicloes
        public async Task<IActionResult> Index()
        {
              return _context.TblCiclos != null ? 
                          View(await _context.TblCiclos.ToListAsync()) :
                          Problem("Entity set 'EscuelaContext.TblCiclos'  is null.");
        }

        // GET: TblCicloes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TblCiclos == null)
            {
                return NotFound();
            }

            var tblCiclo = await _context.TblCiclos
                .FirstOrDefaultAsync(m => m.IdCiclo == id);
            if (tblCiclo == null)
            {
                return NotFound();
            }

            return View(tblCiclo);
        }

        // GET: TblCicloes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TblCicloes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCiclo,NombreCiclo,CveCiclo")] TblCiclo tblCiclo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tblCiclo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tblCiclo);
        }

        // GET: TblCicloes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TblCiclos == null)
            {
                return NotFound();
            }

            var tblCiclo = await _context.TblCiclos.FindAsync(id);
            if (tblCiclo == null)
            {
                return NotFound();
            }
            return View(tblCiclo);
        }

        // POST: TblCicloes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCiclo,NombreCiclo,CveCiclo")] TblCiclo tblCiclo)
        {
            if (id != tblCiclo.IdCiclo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tblCiclo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TblCicloExists(tblCiclo.IdCiclo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tblCiclo);
        }

        // GET: TblCicloes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TblCiclos == null)
            {
                return NotFound();
            }

            var tblCiclo = await _context.TblCiclos
                .FirstOrDefaultAsync(m => m.IdCiclo == id);
            if (tblCiclo == null)
            {
                return NotFound();
            }

            return View(tblCiclo);
        }

        // POST: TblCicloes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TblCiclos == null)
            {
                return Problem("Entity set 'EscuelaContext.TblCiclos'  is null.");
            }
            var tblCiclo = await _context.TblCiclos.FindAsync(id);
            if (tblCiclo != null)
            {
                _context.TblCiclos.Remove(tblCiclo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TblCicloExists(int id)
        {
          return (_context.TblCiclos?.Any(e => e.IdCiclo == id)).GetValueOrDefault();
        }
    }
}

Controllers/TblGrupoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ControlEscolar.Models;

namespace ControlEscolar.Controllers
{
    public class TblGrupoesController : Controller
    {
        private readonly EscuelaContext _context;

        public TblGrupoesController(EscuelaContext context)
        {
            _context = context;
        }

        // GET: TblGrupoes
        public async Task<IActionResult> Index()
        {
              return _context.TblGrupos != null ? 
                          View(await _context.TblGrupos.ToListAsync()) :
                          Problem("Entity set 'EscuelaContext.TblGrupos'  is null.");
        }

        // GET: TblGrupoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TblGrupos == null)
            {
                return NotFound();
            }

            var tblGrupo = await _context.TblGrupos
                .FirstOrDefaultAsync(m => m.IdGrupo == id);
            if (tblGrupo == null)
            {
                return NotFound();
            }

            return View(tblGrupo);
        }

        // GET: TblGrupoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TblGrupoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdGrupo,NombreGrupo,Grado")] TblGrupo tblGrupo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tblGrupo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tblGrupo);
        }

        // GET: TblGrupoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TblGrupos == null)
            {
                return NotFound();
            }

            var tblGrupo = await _context.TblGrupos.FindAsync(id);
            if (tblGrupo == null)
            {
                return NotFound();
            }
            return View(tblGrupo);
        }

        // POST: TblGrupoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdGrupo,NombreGrupo,Grado")] TblGrupo tblGrupo)
        {
            if (id != tblGrupo.IdGrupo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tblGrupo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TblGrupoExists(tblGrupo.IdGrupo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tblGrupo);
        }

        // GET: TblGrupoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TblGrupos == null)
            {
                return NotFound();
            }

            var tblGrupo = await _context.TblGrupos
                .FirstOrDefaultAsync(m => m.IdGrupo == id);
            if (tblGrupo == null)
            {
                return NotFound();
            }

            return View(tblGrupo);
        }

        // POST: TblGrupoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TblGrupos == null)
            {
                return Problem("Entity set 'EscuelaContext.TblGrupos'  is null.");
            }
            var tblGrupo = await _context.TblGrupos.FindAsync(id);
            if (tblGrupo != null)
            {
                _context.TblGrupos.Remove(tblGrupo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TblGrupoExists(int id)
        {
          return (_context.TblGrupos?.Any(e => e.IdGrupo == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ControlEscolar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ControlEscolar.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ControlEscolar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TblAlumnoes" asp-action="Index">Alumnos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TblProfesors" asp-action="Index">Profesores</a>
                        </li>
                       


                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                            <ul class="navbar-nav">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Catalogos
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                        <li>
                                            <a class="dropdown-item" asp-area="" asp-controller="TblCicloes" asp-action="Index">Ciclo Escolar</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" asp-area="" asp-controller="TblGrupoes" asp-action="Index">Grupos</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" asp-area="" asp-controller="TblMateriums" asp-action="Index">Materias</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" asp-area="" asp-controller="TblTipoCalificacions" asp-action="Index">Cat. Tipo Calificacion</a>
                                        </li>
                                        <li >
                                            <a class="dropdown-item" asp-area="" asp-controller="TblCicloGrupoMateriums" asp-action="Index">Asignar Grupos y Materias </a>
                                        </li>
                                        <li >
                                            <a class="dropdown-item" asp-area="" asp-controller="TblGrupoProfAlumnoes" asp-action="Index">Asignar Profesores y Alumnos</a>
                                        </li>

                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
                        </li>





                       
                    </ul>

                   



                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ControlEscolar - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>